name: CI Pipeline & Docker Build

on:
  push:
    branches: [ main ]

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO_NAME }}.mlflow"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version
          ls -R

      - name: Install dependencies
        run: pip install mlflow dagshub pandas scikit-learn

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject --env-manager=local --experiment-name Water_Quality

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          run_id=$(cat MLProject/run_id.txt)
          echo "RUN_ID=$run_id" >> $GITHUB_ENV
          echo "Detected Run ID: $run_id"

      - name: Install Python dependencies
        run: pip install mlflow dagshub

      - name: Upload to Github
        uses: actions/upload-artifact@v4
        with:
          name: run-id-and-model artifact
          path: |
            MLProject/run_id.txt
            MLProject/model/

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow models build-docker \
            -m "MLProject/model" \
            -n "${{ secrets.DOCKER_USERNAME }}/water-quality-model:latest" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/water-quality-model:latest ${{ secrets.DOCKER_USERNAME }}/water-quality-model:${{ env.RUN_ID }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/water-quality-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/water-quality-model:${{ env.RUN_ID }}